CREATE TABLE producto (
    id BIGSERIAL PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    precio NUMERIC(15,2) NOT NULL,
    id_empresa INTEGER,
    iva VARCHAR(20) NOT NULL,
    controla_stock BOOLEAN DEFAULT FALSE,
    status boolean DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW()
);

-- ENUM
create type tipo_movimiento_stock as enum (
  'ENTRADA',
  'SALIDA'
);
create table movimiento_stock (
  id bigint generated by default as identity primary key,
  id_producto bigint not null,
  id_empresa INTEGER not null,
  cantidad numeric not null,
  tipo tipo_movimiento_stock not null,
  create_at timestamp not null default now(),
  constraint fk_movimiento_producto
    foreign key (id_producto)
    references producto(id)
);